### ISSUE TITLE
ERROR: Maven Home /var/jenkins_home/tools/hudson.tasks.Maven_MavenInstallation/Maven doesnt exist

### ISSUE THREAD

**Issue by owen2016** [jenkins-zh/docker-zh#14]
使用了定制化的jenkins-zh, 在global tool 里配置了maven , 启动build ,提示下面error. 不能自动安装maven

Invalid tool ID 3.6.3
Invalid tool ID 3.6.3
ERROR: Maven Home /var/jenkins_home/tools/hudson.tasks.Maven_MavenInstallation/Maven doesnt exist
Finished: FAILURE

**Comment by LinuxSuRen** [comment]
感谢反馈问题。我怀疑是国内源的问题，你切换成原先的源试试

**Comment by LinuxSuRen** [comment]
使用的镜像为 `jenkinszh/jenkins-zh:lts` 对吗？

**Comment by owen2016** [comment]
> 使用的镜像为 `jenkinszh/jenkins-zh:lts` 对吗？

是的，也用了 tag:latest，同样的问题

**Comment by owen2016** [comment]
> 使用的镜像为 `jenkinszh/jenkins-zh:lts` 对吗？

用apt 装的，maven version list 都可以显示出来

**Comment by LinuxSuRen** [comment]
已经确定了，是国内源的缺陷。修改下更新中心为原来的就可以了。

**Comment by LinuxSuRen** [comment]
weelly 版本的 Jenkins 已经可以正常获取 Maven 以及 JDK 工具列表，测试命令如下：
`docker run --rm -p 8080:8080 jenkinszh/jenkins-k8s:2.223`

fixed by jenkins-zh/mirror-adapter#10 and jenkins-zh/mirror-proxy#14. I use this [script](https://github.com/jenkins-zh/update-center-mirror/blob/master/.github/workflows/mirror.yaml) to update those files daily.

Once I test pass the TLS versions, I'll make a note here.

**Comment by LinuxSuRen** [comment]
I've tested the latest LTS version by the following command:

`docker run --rm -p 8080:8080 jenkinszh/jenkins-k8s:2.204.5`

It's all ok now.
